# PROBLEM STATEMENT

The following assignment concerns the numpy.random package in Python. You are
required to create a Jupyter notebook explaining the use of the package, including
detailed explanations of at least five of the distributions provided for in the package.
There are four distinct tasks to be carried out in your Jupyter notebook.
1. Explain the overall purpose of the package.
2. Explain the use of the “Simple random data” and “Permutations” functions.
3. Explain the use and purpose of at least five “Distributions” functions.
4. Explain the use of seeds in generating pseudorandom numbers.

## Section 1. Explain the overall purpose of the package.

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more. NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes.

Numpy.random package is a sub-package of a numpy package in Python.It's purpose is to generate a random numbers. Numpy.random package is divided into 4 sections:
1. Simple random data- contains 10 functions
![Simple random data](simple_random_data.jpg)
2. Permutations- contains 2 functions
![Permutations](permutations.jpg)
3. Distributions- contains 35 functions
![Distributions](distributions.jpg)
4. Random generator- contains 4 functions
![Random generator](random_generator.jpg)

In [1]:
# Import packages
import numpy as np
import matplotlib.pyplot as plt

## Section 2. Explain the use of the “Simple random data” and “Permutations” functions.

### Simple random data:

You can use Simple random data functions if you want to generate some random data for everyday purposes.I explain first five functions from this section.

### [numpy.random.rand](https://docs.scipy.org/doc/numpy-1.15.4/reference/generated/numpy.random.rand.html#numpy.random.rand)
Random values in a given shape.

In [2]:
# Returns random float between 0 and 1.
np.random.rand()

0.7294799606500463

In [3]:
# Returns 10 random floats between 0 and 1.
np.random.rand(10)

array([0.43431678, 0.0312438 , 0.00978969, 0.24593377, 0.020191  ,
       0.18061869, 0.41774853, 0.89760113, 0.52257464, 0.53041358])

In [4]:
# Returns an array or random floats between 0 and 1 with the given shape.
np.random.rand(5,3)

array([[0.22866774, 0.36503142, 0.06992692],
       [0.0477679 , 0.14945968, 0.43818533],
       [0.3341869 , 0.14593002, 0.90314773],
       [0.15343139, 0.28042336, 0.72976677],
       [0.22657164, 0.5094706 , 0.9918589 ]])

### [numpy.random.randn](https://docs.scipy.org/doc/numpy-1.15.4/reference/generated/numpy.random.randn.html#numpy.random.randn)
Return a sample (or samples) from the “standard normal” distribution.

In [5]:
# Returns random float from the standard normal distribution.
np.random.randn()

-1.026056818758633

In [6]:
# Returns 10 random floats from the standard normal distribution.
np.random.randn(10)

array([ 0.7147396 , -0.81678941,  0.39264322,  0.07642065,  0.24031181,
        0.67130212, -1.40444079,  1.45429878, -0.6752589 ,  2.12688951])

In [7]:
# Returns an array of random floats from the standard normal distribution with the given shape.
np.random.randn(5,3)

array([[ 1.82393598, -0.39278024, -0.0396652 ],
       [-0.26929022,  0.45463206,  0.73600125],
       [-0.37259192, -0.78447582, -0.7826523 ],
       [ 0.81769541, -0.20834363, -0.13662558],
       [-0.41051064, -0.04841334,  1.29398183]])

### [numpy.random.randint](https://docs.scipy.org/doc/numpy-1.15.4/reference/generated/numpy.random.randint.html#numpy.random.randint)
Return random integers from low (inclusive) to high (exclusive).

In [8]:
# Returns random integer from 0(inclusive) to 5(exclusive).
np.random.randint(5)

1

In [9]:
# Returns random integer from 5(inclusive) to 10(exclusive).
np.random.randint(5,10)

6

In [10]:
# Returns an array of random integers between 5(inclusive) and 10 (exclusive) with the given shape.
np.random.randint(5,10, size=(2,4))

array([[5, 8, 6, 9],
       [5, 8, 7, 6]])

### [numpy.random.random_integers](https://docs.scipy.org/doc/numpy-1.15.4/reference/generated/numpy.random.random_integers.html#numpy.random.random_integers)
Random integers of type np.int between low and high, inclusive.

This function is deprecated.

### [numpy.random.random_sample](https://docs.scipy.org/doc/numpy-1.15.4/reference/generated/numpy.random.random_sample.html#numpy.random.random_sample)
Return random floats in the half-open interval [0.0, 1.0).

In [11]:
# Returns random float between 0.0 and 1.0.
np.random.random_sample()

0.38335017569230956

In [12]:
# Returns 5 random floats between 0.0 and 1.0.
np.random.random_sample(5)

array([0.32832674, 0.62416249, 0.85332799, 0.71184518, 0.70179271])

In [13]:
# Returns an array of random floats between 0.0 and 1.0. with the given shape.
np.random.random_sample((5, 3))

array([[0.87093293, 0.58489207, 0.85569791],
       [0.14725314, 0.24031192, 0.79376264],
       [0.59460994, 0.40001616, 0.77658263],
       [0.58263569, 0.51999882, 0.7753614 ],
       [0.75754459, 0.1010781 , 0.90578568]])

### Permutations



## Section 3. Explain the use and purpose of at least five “Distributions” functions.

### Distributions



## Section 4. Explain the use of seeds in generating pseudorandom numbers.

### Random generator



## References

[SciPy.org- Random sampling (numpy.random)](https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.random.html)

[StackOverflow- How to embed image](https://stackoverflow.com/questions/32370281/how-to-embed-image-or-picture-in-jupyter-notebook-either-from-a-local-machine-o)

[SciPy.org- What is Numpy](https://docs.scipy.org/doc/numpy/user/whatisnumpy.html)