# Problem statement

The following assignment concerns the numpy.random package in Python. You are
required to create a Jupyter notebook explaining the use of the package, including
detailed explanations of at least five of the distributions provided for in the package.
There are four distinct tasks to be carried out in your Jupyter notebook.
1. Explain the overall purpose of the package.
2. Explain the use of the “Simple random data” and “Permutations” functions.
3. Explain the use and purpose of at least five “Distributions” functions.
4. Explain the use of seeds in generating pseudorandom numbers.

# Section 1. Explain the overall purpose of the package.

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more. NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes.

Numpy.random package is a sub-package of a numpy package in Python.It's purpose is to generate a random numbers. Numpy.random package is divided into 4 sections:
1. Simple random data- contains 10 functions
![Simple random data](simple_random_data.jpg)
2. Permutations- contains 2 functions
![Permutations](permutations.jpg)
3. Distributions- contains 35 functions
![Distributions](distributions.jpg)
4. Random generator- contains 4 functions
![Random generator](random_generator.jpg)

In [1]:
# Import packages
import numpy as np
import matplotlib.pyplot as plt

# Section 2. Explain the use of the “Simple random data” and “Permutations” functions.

## Simple random data

You can use Simple random data functions if you want to generate some random data for everyday purposes.

### [numpy.random.rand](https://docs.scipy.org/doc/numpy-1.15.4/reference/generated/numpy.random.rand.html#numpy.random.rand)(d0, d1, …, dn)

Random values in a given shape.

In [2]:
# Returns random float between 0 and 1.
np.random.rand()

0.01984151425175873

In [3]:
# Returns 10 random floats between 0 and 1.
np.random.rand(10)

array([0.5164533 , 0.74139095, 0.22978903, 0.06025924, 0.45990217,
       0.14442221, 0.16761022, 0.77822452, 0.90185174, 0.64652329])

In [4]:
# Returns an array or random floats between 0 and 1 with the given shape.
np.random.rand(5,3)

array([[0.54828798, 0.82290586, 0.43643375],
       [0.39222713, 0.6334644 , 0.69936043],
       [0.93824612, 0.17295141, 0.07759592],
       [0.94597381, 0.18887272, 0.33970247],
       [0.98199567, 0.79118492, 0.737845  ]])

### [numpy.random.randn](https://docs.scipy.org/doc/numpy-1.15.4/reference/generated/numpy.random.randn.html#numpy.random.randn)(d0, d1, …, dn)
Return a sample (or samples) from the “standard normal” distribution.

In [5]:
# Returns random float from the standard normal distribution.
np.random.randn()

1.2990428492392498

In [6]:
# Returns 10 random floats from the standard normal distribution.
np.random.randn(10)

array([-2.69196827,  0.11593364, -0.33546438,  1.23583265, -1.17640467,
        0.59967115,  1.63892493,  1.21721646, -1.19516035,  0.93196233])

In [7]:
# Returns an array of random floats from the standard normal distribution with the given shape.
np.random.randn(5,3)

array([[-0.42514285,  1.06361724, -1.18052106],
       [ 0.12521697,  0.2560908 , -0.39719608],
       [ 0.05001475, -0.57742716,  0.796618  ],
       [ 0.14361931,  0.94253177, -0.37369425],
       [-0.77208417,  0.80419892, -0.75028937]])

### [numpy.random.randint](https://docs.scipy.org/doc/numpy-1.15.4/reference/generated/numpy.random.randint.html#numpy.random.randint)(low[, high, size, dtype])
Return random integers from low (inclusive) to high (exclusive).

In [8]:
# Returns random integer from 0(inclusive) to 5(exclusive).
np.random.randint(5)

0

In [9]:
# Returns random integer from 5(inclusive) to 10(exclusive).
np.random.randint(5,10)

5

In [10]:
# Returns an array of random integers between 5(inclusive) and 10 (exclusive) with the given shape.
np.random.randint(5,10, size=(2,4))

array([[6, 6, 6, 5],
       [7, 7, 5, 7]])

### [numpy.random.random_integers](https://docs.scipy.org/doc/numpy-1.15.4/reference/generated/numpy.random.random_integers.html#numpy.random.random_integers)(low[, high, size])

Random integers of type np.int between low and high, inclusive.

This function is deprecated.

### [numpy.random.random_sample](https://docs.scipy.org/doc/numpy-1.15.4/reference/generated/numpy.random.random_sample.html#numpy.random.random_sample)([size])
Return random floats in the half-open interval [0.0, 1.0).

In [11]:
# Returns random float between 0.0 and 1.0.
np.random.random_sample()

0.8309132231757416

In [12]:
# Returns 5 random floats between 0.0 and 1.0.
np.random.random_sample(5)

array([0.22257535, 0.86007463, 0.68877425, 0.66289741, 0.75097926])

In [13]:
# Returns an array of random floats between 0.0 and 1.0. with the given shape.
np.random.random_sample((5, 3))

array([[0.66463851, 0.82353002, 0.03382475],
       [0.1565447 , 0.10151249, 0.18649042],
       [0.56459541, 0.05774122, 0.22139953],
       [0.36620771, 0.3788071 , 0.35686914],
       [0.72141155, 0.67799935, 0.54149992]])

### [numpy.random.random](https://docs.scipy.org/doc/numpy-1.15.4/reference/generated/numpy.random.random.html#numpy.random.random)(size=None)

Return random floats in the half-open interval [0.0, 1.0).

### [numpy.random.ranf](https://docs.scipy.org/doc/numpy-1.15.4/reference/generated/numpy.random.ranf.html#numpy.random.ranf)(size=None)

Return random floats in the half-open interval [0.0, 1.0).

### [numpy.random.sample](https://docs.scipy.org/doc/numpy-1.15.4/reference/generated/numpy.random.sample.html#numpy.random.sample)(size=None)

Return random floats in the half-open interval [0.0, 1.0).

### [numpy.random.choice](https://docs.scipy.org/doc/numpy-1.15.4/reference/generated/numpy.random.choice.html#numpy.random.choice)(a, size=None, replace=True, p=None)

Generates a random sample from a given 1-D array.

In [14]:
# Returns an uniform random sample from np.arange(6) of size 2.
np.random.choice(6, 2)

array([3, 5])

In [15]:
# Returns a non-uniform random sample from np.arange(6) of size 2.
np.random.choice(6, 2, p=[0.1, 0, 0.3, 0.4, 0, 0.2])

array([3, 2], dtype=int64)

In [16]:
# Returns a uniform random sample from np.arange(6) of size 2 without replacement.
np.random.choice(6, 2, replace=False)

array([3, 4])

In [17]:
# Returns a non-uniform random sample from np.arange(6) of size 2 without replacement.
np.random.choice(6, 2, replace=False, p=[0.1, 0, 0.3, 0.4, 0, 0.2])

array([2, 3])

### [numpy.random.bytes](https://docs.scipy.org/doc/numpy-1.15.4/reference/generated/numpy.random.bytes.html#numpy.random.bytes)(length)

Return random bytes.

In [18]:
# Returns random bytes
np.random.bytes(15)

b"\xf7\xd2't\xdaT\xa1\xd51\x91\xea\xaf\x00\xdb\xcb"

## Permutations

### [numpy.random.shuffle](https://docs.scipy.org/doc/numpy-1.15.4/reference/generated/numpy.random.shuffle.html#numpy.random.shuffle)(x)

Modify a sequence in-place by shuffling its contents.

In [19]:
# Shuffle the list of integers from 0 to 14 inclusive.
arr = np.arange(15)
np.random.shuffle(arr)
arr

array([ 6,  8,  1,  5,  2,  0,  4, 11, 12, 13,  7,  9,  3, 10, 14])

In [20]:
# Shuffle the array with the given shape.
arr = np.arange(6).reshape((3, 2))
np.random.shuffle(arr)
arr

array([[0, 1],
       [4, 5],
       [2, 3]])

### [numpy.random.permutation](https://docs.scipy.org/doc/numpy-1.15.4/reference/generated/numpy.random.permutation.html#numpy.random.permutation)(x)

Randomly permute a sequence, or return a permuted range.

In [21]:
# Returns a permuted sequence of integers 0-5 inclusive.
np.random.permutation(6)

array([3, 5, 1, 0, 4, 2])

In [22]:
# Returns a permuted sequence of given integers.
np.random.permutation([2, 4, 6, 8, 10, 12])

array([12,  8,  4,  6,  2, 10])

In [23]:
# Make a copy and shuffle the elements randomly.
arr = np.arange(6).reshape((2, 3))
np.random.permutation(arr)

array([[3, 4, 5],
       [0, 1, 2]])

# Section 3. Explain the use and purpose of at least five “Distributions” functions.

## Distributions



# Section 4. Explain the use of seeds in generating pseudorandom numbers.

## Random generator



# References

[SciPy.org- Random sampling (numpy.random)](https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.random.html)

[StackOverflow- How to embed image](https://stackoverflow.com/questions/32370281/how-to-embed-image-or-picture-in-jupyter-notebook-either-from-a-local-machine-o)

[SciPy.org- What is Numpy](https://docs.scipy.org/doc/numpy/user/whatisnumpy.html)